export const BASE_URL ="http://137.184.122.0";

//All Dispatch Types Name
export const LOGIN_TAB = 'LOGIN_TAB';
export const REGISTER_TAB = 'REGISTER_TAB';
export const REGISTER_API_STARTLOADING = 'REGISTER_API_STARTLOADING';
export const REGISTER_API_STOPLOADING = 'REGISTER_API_STOPLOADING';

export const VERIFY_API_STARTLOADING = 'VERIFY_API_STARTLOADING';
export const VERIFY_API_STOPLOADING = 'VERIFY_API_STOPLOADING';

export const USER_TOKEN = 'USER_AUTH_TOKEN';
export const GET_LOCAL_TOKEN = 'GET_LOCAL_TOKEN';
export const LOG_OUT= 'LOG_OUT'